#server:
#  port: 8082

spring:
  application:
    name: QUESTION-SERVICE
#
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/


  spring:
    http:
      netty:
        maxHeaderSize: 16384